---
baseUrl: "/"
enableRobotsTXT: true
languageCode: en-us
relativeURLs: true
title: MIT OpenCourseWare
theme: ["course-offline", "course", "base-theme"]
ignoreErrors: ["error-remote-getjson"]
outputFormats:
  coursedata:
    mediaType: "application/json"
    baseName: "data"
    isPlainText: true
  contentmap:
    mediaType: "application/json"
    baseName: "content_map"
    isPlainText: true
outputs:
  home:
    - coursedata
    - contentmap
    - HTML
  page:
    - coursedata
    - HTML
  section:
    - coursedata
    - HTML
security:
  funcs:
    getenv:
      - ^HUGO_
      - API_BEARER_TOKEN
      - GTM_ACCOUNT_ID
      - RESOURCE_BASE_URL
      - STATIC_API_BASE_URL
      - OCW_STUDIO_BASE_URL
      - OCW_IMPORT_STARTER_SLUG
      - COURSE_BASE_URL
      - SITEMAP_DOMAIN
markup:
  highlight:
    style: colorful
taxonomies:
  learning_resource_type: learning_resource_types
permalinks:
  learning_resource_types: "/resources/:slug/"
