---
baseUrl: "/"
enableRobotsTXT: true
languageCode: en-us
relativeURLs: true
title: MIT OpenCourseWare
theme: ["course-offline-v2", "course-v3", "base-theme"]
ignoreErrors: ["error-remote-getjson"]
outputFormats:
  coursedata:
    mediaType: "application/json"
    baseName: "data"
    isPlainText: true
  contentmap:
    mediaType: "application/json"
    baseName: "content_map"
    isPlainText: true
outputs:
  home:
    - coursedata
    - contentmap
    - HTML
  page:
    - coursedata
    - HTML
  section:
    - coursedata
    - HTML
security:
  funcs:
    getenv:
      - ^HUGO_
      - WEBPACK_HOST
      - WEBPACK_PORT
      - API_BEARER_TOKEN
      - GTM_ACCOUNT_ID
      - RESOURCE_BASE_URL
      - STATIC_API_BASE_URL
      - OCW_STUDIO_BASE_URL
      - OCW_IMPORT_STARTER_SLUG
      - OCW_COURSE_STARTER_SLUG
      - COURSE_BASE_URL
      - SITEMAP_DOMAIN
      - SENTRY_DSN
  http:
    methods:
      - (?i)GET|HEAD
markup:
  highlight:
    style: colorful
  goldmark:
    renderer:
      unsafe: true
mediaTypes:
  application/zip:
    suffixes:
      - zip
taxonomies:
  learning_resource_type: learning_resource_types
permalinks:
  learning_resource_types: "/resources/:slug/"
