---
name: CI
on: [push]
jobs:
  yaml-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 17.3.0
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
        with:
          python-version: "3.13.x"
      - run: yarn install --frozen-lockfile
      - run: pip install -r requirements.txt
      - name: Lint
        run: yamllint .
      - name: Formatting
        run: yarn fmt:check
