---
name: CI
on: [push]
jobs:
  yaml-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 17.3.0
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5
        with:
          python-version: "3.9.x"
      - run: yarn install --frozen-lockfile
      - run: pip install -r requirements.txt
      - name: Lint
        run: yamllint .
      - name: Formatting
        run: yarn fmt:check
