---
name: CI
on: [push]
jobs:
  yaml-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: 22
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: "3.13.x"
      - run: yarn install --frozen-lockfile
      - run: pip install -r requirements.txt
      - name: Lint
        run: yamllint .
      - name: Formatting
        run: yarn fmt:check
